const ErrorMessage = {
  PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  USER_CREATED: "USER_CREATED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  PASSWORD_NOT_MATCH: "PASSWORD_NOT_MATCH",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  ACCOUNT_HAS_BEEN_DELETED: "ACCOUNT_HAS_BEEN_DELETED",
  WRONG_OLD_PASSWORD: "WRONG_OLD_PASSWORD",
  PLEASE_VERIFY_OTP: "PLEASE_VERIFY_OTP",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  THE_NEW_PASSWORD_MUST_BE_DIFFERENT_FROM_THE_OLD_PASSWORD:
    "THE_NEW_PASSWORD_MUST_BE_DIFFERENT_FROM_THE_OLD_PASSWORD",
  INVALID_REQUEST: "INVALID_REQUEST",
  KEY_TOKEN_NOT_FOUND: "KEY_TOKEN_NOT_FOUND",
  INVALID_REQUEST_TOKEN: "INVALID_REQUEST_TOKEN",
  INVALID_USER_ID: "INVALID_USER_ID",
  TOKEN_INVALID: "TOKEN_INVALID",
  CHANGE_PASS_SUCCESS_PLEASE_LOGIN_AGAIN:
    "CHANGE_PASS_SUCCESS_PLEASE_LOGIN_AGAIN",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  TIMEZONE_IS_REQUIRED: "TIMEZONE_IS_REQUIRED",
  PLEASE_TRY_AGAIN: "PLEASE_TRY_AGAIN",
  USER_CAN_NOT_ACCESS_PROCEDURE_OF_THIS_BU:
    "USER_CAN_NOT_ACCESS_PROCEDURE_OF_THIS_BU",
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  ACTIVED: "ACTIVED",
  DEACTIVATED: "DEACTIVATED",
  PLEASE_CHANGE_PASSWORD: "PLEASE_CHANGE_PASSWORD"
};

module.exports = ErrorMessage;
